# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj = bld.create_ns3_program('energy-aware-epidemic-example', ['epidemic-routing', 'wifi', 'energy', 'applications', 'netanim'])
    obj.source = 'energy-aware-epidemic-example.cc'

